services:
  frontend:
    image: talharehman2727/product_frontend:1.0.0
    ports:
      - "5000:80"
    networks:
      - product_backend_default

networks:
  product_backend_default:
    external: true
