services:
  frontend:
    image: talharehman2727/product_frontend:latest
    ports:
      - "5000:80"
    networks:
      - product_backend_default
    depends_on:
      - backend

networks:
  product_backend_default:
    external: true
