services:
  frontend:
    image: frontend:latest
    ports:
      - "5000:80"
    networks:
      - product_backend_default  # backend ka correct network attach karo

networks:
  product_backend_default:
    external: true
